// Generated by CoffeeScript 1.12.6
(function() {
  var Studium;

  Studium = {
    Semester1: {
      Name: "Semester 1",
      Fächer: [
        {
          Name: "Grundlagen der Informatik 1",
          Credits: 5,
          SWS: "2/0/2"
        }, {
          Name: "Mathamatik",
          Credits: 2,
          SWS: "2/0/2"
        }
      ]
    }
  };

}).call(this);


